FROM golang:1.18.2

WORKDIR ./cmd/server

EXPOSE 8081

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v ./cmd/server




CMD ["./server"]
